# Generated by Django 3.1.7 on 2021-05-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
