# Generated by Django 3.1.7 on 2021-05-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default=None, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='processor_freq',
            field=models.CharField(max_length=255, verbose_name='Количество ядер процессора'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
